// Mock data matching API response structure (ready for backend integration)

export const PROJECTS_PAGE_META = {
  title: "Our Projects",
  subtitle: "A portfolio of successful projects across diverse sectors.",
  bannerImage: "/images/faden/projects-banner.webp",
};

// Service categories
const SERVICES = {
  engineering: {
    id: "fed36a99-7848-42fa-87b2-666be37ce2a3",
    name: "Integrated Engineering Works",
    slug: "integrated-engineering-works",
  },
  construction: {
    id: "89d4afb2-e665-4327-a2af-9afd7232a91c",
    name: "Integrated Construction Works",
    slug: "integrated-construction-works",
  },
  mep: {
    id: "a6b44f1b-f7f6-4f3c-ad3f-68368bc4a278",
    name: "MEP Works",
    slug: "mep-works",
  },
  water: {
    id: "33d47a6c-11ea-445c-a0f7-c56b77514f78",
    name: "Sewage and Water Treatment Plants",
    slug: "sewage-and-water-treatment-plants",
  },
  roads: {
    id: "118b8d3a-6064-4697-91a9-fbf07242e7ee",
    name: "Roads & Infrastructure Works",
    slug: "roads-and-infrastructure-works",
  },
};

export const PROJECTS_ITEMS = [
  // Integrated Engineering Works (6)
  {
    id: "d92212e1-ee28-480c-a5d8-22c4e327ddc4",
    title: "King Road Tower - JEDDAH",
    slug: "king-road-tower-jeddah",
    img: "/images/faden/projects-page-1.webp",
    status: "Finished",
    partnershipType: "Faden Only",
    order: 1,
    client: "Al Amoudi Holding",
    location: "Jeddah, Saudi Arabia",
    service: SERVICES.engineering,
    createdAt: "2024-01-15T00:00:00.000Z",
  },
  {
    id: "0f4638e7-8d41-43db-a924-50834442a802",
    title: "American International School",
    slug: "american-international-school",
    img: "/images/faden/projects-page-2.webp",
    status: "Finished",
    partnershipType: "Faden Only",
    order: 2,
    client: "AIS Educational Group",
    location: "Riyadh, Saudi Arabia",
    service: SERVICES.engineering,
    createdAt: "2024-02-10T00:00:00.000Z",
  },
  {
    id: "061718ad-8cce-4707-88c4-39a838eadf76",
    title: "Al Muhaiza Residential Palace",
    slug: "al-muhaiza-residential-palace",
    img: "/images/faden/projects-page-3.webp",
    status: "Finished",
    partnershipType: "With Global Energy",
    order: 3,
    client: "Private Client",
    location: "Riyadh, Saudi Arabia",
    service: SERVICES.engineering,
    createdAt: "2024-03-05T00:00:00.000Z",
  },

  // Integrated Construction Works (3)
  {
    id: "945e0cae-eebf-4d2a-8e95-4b3458c04606",
    title: "Royal Palace (Um Alhamam)",
    slug: "royal-palace-um-alhamam",
    img: "/images/faden/projects-page-4.webp",
    status: "Finished",
    partnershipType: "Faden Only",
    order: 4,
    client: "Royal Protocol",
    location: "Um Alhamam, Riyadh, Saudi Arabia",
    service: SERVICES.construction,
    createdAt: "2024-04-01T00:00:00.000Z",
  },
  {
    id: "916e4efe-26f3-452f-a4cb-15fee2cb022c",
    title: "Salboukh Air Operation Building",
    slug: "salboukh-air-operation-building",
    img: "/images/faden/projects-page-5.webp",
    status: "Finished",
    partnershipType: "With Global Energy",
    order: 5,
    client: "Aviation Authority",
    location: "Salboukh, Saudi Arabia",
    service: SERVICES.construction,
    createdAt: "2024-04-15T00:00:00.000Z",
  },
  {
    id: "55e1e099-e9d3-4e2f-ad31-9590c3cd8368",
    title: "King Faisal Air Academy-VIP Terminal",
    slug: "king-faisal-air-academy-vip-terminal",
    img: "/images/faden/projects-page-6.webp",
    status: "Finished",
    partnershipType: "Faden Only",
    order: 6,
    client: "Royal Saudi Air Force",
    location: "Riyadh, Saudi Arabia",
    service: SERVICES.construction,
    createdAt: "2024-05-01T00:00:00.000Z",
  },

  // MEP Works (3)
  {
    id: "0f1171e8-bff6-43e5-a843-30bca2e277a6",
    title: "ARGO Egypt",
    slug: "argo-egypt",
    img: "/images/faden/projects-page-7.webp",
    status: "Finished",
    partnershipType: "With Global Energy",
    order: 7,
    client: "ARGO Industrial",
    location: "Cairo, Egypt",
    service: SERVICES.mep,
    createdAt: "2024-05-20T00:00:00.000Z",
  },
  {
    id: "0f1171e8-bff6-43e5-a843-30bca2e277a7",
    title: "Scientific Research & Tech City",
    slug: "scientific-research-tech-city",
    img: "/images/faden/projects-page-8.webp",
    status: "Finished",
    partnershipType: "Faden Only",
    order: 8,
    client: "Ministry of Science",
    location: "Riyadh, Saudi Arabia",
    service: SERVICES.mep,
    createdAt: "2024-06-05T00:00:00.000Z",
  },
  {
    id: "0f1171e8-bff6-43e5-a843-30bca2e277a8",
    title: "Cairo West Supercritical Power Plant",
    slug: "cairo-west-supercritical-power-plant",
    img: "/images/faden/projects-page-9.webp",
    status: "Finished",
    partnershipType: "With Global Energy",
    order: 9,
    client: "Egyptian Electricity Holding",
    location: "Cairo, Egypt",
    service: SERVICES.mep,
    createdAt: "2024-06-20T00:00:00.000Z",
  },

  // Sewage and Water Treatment Plants (3)
  {
    id: "e921aba6-e9b7-430e-93cb-afa86681cb85",
    title: "Al-Alamein SWRO Plant",
    slug: "al-alamein-swro-plant",
    img: "/images/faden/projects-page-10.webp",
    status: "Finished",
    partnershipType: "With Global Energy",
    order: 10,
    client: "National Water Company",
    location: "Al-Alamein, Egypt",
    service: SERVICES.water,
    createdAt: "2024-07-10T00:00:00.000Z",
  },
  {
    id: "e921aba6-e9b7-430e-93cb-afa86681cb86",
    title: "El-Husseiniya & Saoud WTPs",
    slug: "el-husseiniya-saoud-wtps",
    img: "/images/faden/projects-page-11.webp",
    status: "In Progress",
    partnershipType: "Faden Only",
    order: 11,
    client: "Ministry of Water",
    location: "Egypt",
    service: SERVICES.water,
    createdAt: "2024-08-01T00:00:00.000Z",
  },
  {
    id: "e921aba6-e9b7-430e-93cb-afa86681cb87",
    title: "Abo Jalal WTP",
    slug: "abo-jalal-wtp",
    img: "/images/faden/projects-page-12.webp",
    status: "Finished",
    partnershipType: "With Global Energy",
    order: 12,
    client: "National Water Company",
    location: "Saudi Arabia",
    service: SERVICES.water,
    createdAt: "2024-08-20T00:00:00.000Z",
  },

  // Roads & Infrastructure Works (3)
  {
    id: "62762e6c-b5b4-4ccd-8e5e-6bfb907e20b6",
    title: "Marassi Blanca 85",
    slug: "marassi-blanca-85",
    img: "/images/faden/projects-page-13.webp",
    status: "Finished",
    partnershipType: "Faden Only",
    order: 13,
    client: "Marassi Development",
    location: "North Coast, Egypt",
    service: SERVICES.roads,
    createdAt: "2024-09-10T00:00:00.000Z",
  },
  {
    id: "62762e6c-b5b4-4ccd-8e5e-6bfb907e20b7",
    title: "SODIC Westown Irrigation System",
    slug: "sodic-westown-irrigation-system",
    img: "/images/faden/projects-page-14.webp",
    status: "In Progress",
    partnershipType: "With Global Energy",
    order: 14,
    client: "SODIC",
    location: "West Cairo, Egypt",
    service: SERVICES.roads,
    createdAt: "2024-09-25T00:00:00.000Z",
  },
  {
    id: "62762e6c-b5b4-4ccd-8e5e-6bfb907e20b8",
    title: "Westown Residence Block 26 ONE 16",
    slug: "westown-residence-block-26",
    img: "/images/faden/projects-page-15.webp",
    status: "Finished",
    partnershipType: "Faden Only",
    order: 15,
    client: "SODIC",
    location: "West Cairo, Egypt",
    service: SERVICES.roads,
    createdAt: "2024-10-05T00:00:00.000Z",
  },

  // Additional Engineering Works (3 more)
  {
    id: "0f4638e7-8d41-43db-a924-50834442a803",
    title: "Park Inn Hotel - By Radisson",
    slug: "park-inn-hotel-by-radisson",
    img: "/images/faden/projects-page-16.webp",
    status: "Finished",
    partnershipType: "Faden Only",
    order: 16,
    client: "Radisson Hospitality",
    location: "Riyadh, Saudi Arabia",
    service: SERVICES.engineering,
    createdAt: "2024-10-20T00:00:00.000Z",
  },
  {
    id: "0f4638e7-8d41-43db-a924-50834442a804",
    title: "Jockey Club",
    slug: "jockey-club",
    img: "/images/faden/projects-page-17.webp",
    status: "Finished",
    partnershipType: "With Global Energy",
    order: 17,
    client: "Riyadh Equestrian Society",
    location: "Riyadh, Saudi Arabia",
    service: SERVICES.engineering,
    createdAt: "2024-11-05T00:00:00.000Z",
  },
  {
    id: "0f4638e7-8d41-43db-a924-50834442a805",
    title: "Private Residence Complex VIP",
    slug: "private-residence-complex-vip",
    img: "/images/faden/projects-page-18.webp",
    status: "Finished",
    partnershipType: "Faden Only",
    order: 18,
    client: "Private Client",
    location: "Riyadh, Saudi Arabia",
    service: SERVICES.engineering,
    createdAt: "2024-11-20T00:00:00.000Z",
  },
];

// Categories with count (auto-computed)
export const PROJECTS_CATEGORIES = Object.values(SERVICES).map((svc) => ({
  ...svc,
  _count: {
    projects: PROJECTS_ITEMS.filter((p) => p.service.id === svc.id).length,
  },
}));

export const PROJECTS_PARTNERSHIP_TYPES = ["Faden Only", "With Global Energy"];

export const PROJECTS_STATUS_OPTIONS = ["Finished", "In Progress"];

export const SORT_OPTIONS = [
  { value: "default", label: "Default Sorting" },
  { value: "name-asc", label: "Name (A - Z)" },
  { value: "name-desc", label: "Name (Z - A)" },
  { value: "newest", label: "Newest First" },
  { value: "oldest", label: "Oldest First" },
];